#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Downloads the Inter + JetBrains Mono variable webfonts and writes
assets/css/fonts.css pointing at the local copies.

Google Fonts serves variable fonts: one woff2 per subset covers every weight
(Inter wght 100-900, JetBrains Mono wght 400-800). The CSS therefore declares
`font-weight: <min> <max>` per face instead of one face per weight -- real
bold glyphs instead of browser-synthesised fake bold.

The landing page must not depend on a third-party CDN at runtime, and the
site is in Russian, so only the cyrillic / cyrillic-ext / latin / latin-ext
subsets are kept.

Run:  python3 tools/fetch_fonts.py
"""
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"}

# google_fonts CSS API -> family, variable weight range, local file prefix
FAMILIES = [
    ("https://fonts.googleapis.com/css2?family=Inter:wght@400..800&display=swap",
     "Inter", "inter"),
    ("https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400..800&display=swap",
     "JetBrains Mono", "jbmono"),
]
SUBSETS = {"cyrillic", "cyrillic-ext", "latin", "latin-ext"}


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read()


def main():
    font_dir = os.path.join(ROOT, "assets", "fonts")
    os.makedirs(font_dir, exist_ok=True)
    blocks, written = [], {}

    for url, family, slug in FAMILIES:
        css = fetch(url).decode("utf-8")
        parts = re.split(r"/\* ([a-z\-]+) \*/", css)
        for i in range(1, len(parts), 2):
            subset = parts[i]
            if subset not in SUBSETS:
                continue
            for face in re.finditer(r"@font-face\s*\{(.*?)\}", parts[i + 1], re.S):
                block = face.group(1)
                # Variable fonts answer with a range: "font-weight: 400 800".
                weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1)
                remote = re.search(r"url\((\S+?)\)", block).group(1)
                urange = re.search(r"unicode-range:\s*([^;]+);", block)
                if remote not in written:
                    name = "%s-var-%s.woff2" % (slug, subset)
                    with open(os.path.join(font_dir, name), "wb") as f:
                        f.write(fetch(remote))
                    written[remote] = name
                    print("%-28s %6.1f KB" % (name, os.path.getsize(os.path.join(font_dir, name)) / 1024))
                blocks.append(
                    "@font-face{font-family:'%s';font-style:normal;font-weight:%s;"
                    "font-display:swap;src:url(../fonts/%s) format('woff2');unicode-range:%s}"
                    % (family, weight, written[remote],
                       urange.group(1).strip() if urange else "U+0000-00FF")
                )

    with open(os.path.join(ROOT, "assets", "css", "fonts.css"), "w", encoding="utf-8") as f:
        f.write("/* Self-hosted variable webfonts (Inter & JetBrains Mono, subsets: cyrillic + latin).\n"
                "   One file per subset covers every weight -- generated by tools/fetch_fonts.py */\n")
        f.write("\n".join(blocks) + "\n")
    print("%d font files, %d @font-face rules" % (len(written), len(blocks)))


if __name__ == "__main__":
    main()
